### PR TITLE
New Post: Merged Resource Packs

### PR DESCRIPTION
**Pull request by KuroiJigoku**

### CODE REVIEW

**Comment by iamdeka** [comment]
Is this even relevant? Why would one need to merge resource packs, not to mention for a Java server?

**Comment by KuroiJigoku** [comment]
In short its like you like the textures of a resource pack and you have to include that, it does not have a sound pack included and now you get another resource pack for it and find that you cannot use multiple resource pack in a server so u merge it and upload it.

**Comment by iamdeka** [comment]
Perhaps include this in the article for resource pack adding instead of making a separate one

**Comment by KuroiJigoku** [comment]
alr

**Pull request closed without merging**
