### PR TITLE
New article: Creating an Account

### PR DESCRIPTION
**Pull request by tp-duolingo**
I have tried some things to create a seperate PR for this hope it works

### CODE REVIEW

**Comment by iamdeka** [comment]
This PR includes changes to the README?

**Comment by tp-duolingo** [comment]
You did NOT help me when I asked how do I  create separate pr's

**Comment by KuroiJigoku** [comment]
breh make different branches containing commits on the same criteria/files and pr that branch

**Comment by tp-duolingo** [comment]
I did that and it didn't work

**Comment by tp-duolingo** [comment]
Talking about it is easy but when it comes to showing it nobody fucking volunteers to

**Comment by addmoreeggs** [comment]
eggs

**Comment by KuroiJigoku** [comment]
- Start by creating a fork of the origin repo.
- Instead of making changes directly to the main branch, Create a new branch based off the `main` branch for your work. Name this branch based on the type of post or update you're planning to add.
- Make your edits and additions (like creating a new post) in this new branch.
- Once you've finished your edits and are satisfied with your changes, create a pr from that branch.
- Always create a new branch for each separate task or post, and avoid making any direct changes to the main branch.
- Keep your fork updated by regularly fetching and merging commits from the origin repo into your fork's `main` branch, but don't edit the `main` branch directly.

**Pull request closed without merging**
