### PR TITLE
New post: Subusers article

### PR DESCRIPTION
**Pull request by theTWIXhunter**
subusers  article made by me and @tp_duolingo (I also comitted a new article for the external start beacuse I linked to it in the subusers article)

### CODE REVIEW

**Comment by theTWIXhunter** [comment]
don't forget to remind me to change the link in the subusers article when the path to the external start guide gets changed
(it currently is falix/dashboard/server/external-start)

**Comment by iamdeka** [comment]
This PR contains other articles other than the one you want to commit. Make a different branch on your fork

**Comment by theTWIXhunter** [comment]
> This PR contains other articles other than the one you want to commit. Make a different branch on your fork

I made one, this was :subusersarticles that I pr’d

**Comment by iamdeka** [comment]
> I made one, this was :subusersarticles that I pr’d

Have you even checked what you are PRing?

**Pull request closed without merging**
