### PR TITLE
New-posts: Add mods, add plugins

### PR DESCRIPTION
**Pull request by theTWIXhunter**
currently in KB-articles/content/_posts/minecraft/modifications/(plugins,mods) but lemme know when to change it to somewhere else

### CODE REVIEW

**Comment by theTWIXhunter** [comment]
I moved the articles to /java(/plugins,/mods) as polled in dc

**Comment by theTWIXhunter** [comment]
deleted the old files (I forgot to do that)

**Comment by iamdeka** [comment]
It should be in `/content/_posts/minecraft/java`, not `/content/_posts/minecraft/java/mods` or `/content/_posts/minecraft/java/plugins` ‼️

**Comment by iamdeka** [comment]
You also disallowed maintainers to edit your PR. Re-open with requested change

**Comment by theTWIXhunter** [comment]
> It should be in `/content/_posts/minecraft/java`, not `/content/_posts/minecraft/java/mods` or `/content/_posts/minecraft/java/plugins` ‼️

Changed it on my branch, lemme reopen the pr

**Pull request closed without merging**
