### PR TITLE
Edit dynmap

### PR DESCRIPTION
**Pull request by Mocab**

### CODE REVIEW

**Comment by iamdeka** [comment]
why is https://github.com/FalixNodes-Software/KB-articles/pull/29/commits/1ba5bc0248b83e044541d33b1efd941b55a53126 included ☹️

**Comment by Mocab** [comment]
> why is [1ba5bc0](https://github.com/FalixNodes-Software/KB-articles/commit/1ba5bc0248b83e044541d33b1efd941b55a53126) included ☹️

whar

**Comment by Dhruv1002** [comment]
No war pls @Mocab

**Comment by iamdeka** [comment]
> > why is [1ba5bc0](https://github.com/FalixNodes-Software/KB-articles/commit/1ba5bc0248b83e044541d33b1efd941b55a53126) included ☹️
> 
> whar

https://github.com/FalixNodes-Software/KB-articles/pull/28

**Review by Mocab — COMMENTED** [review]
ready for review ig

**Pull request merged**
