### PR TITLE
New post: multiverse

### PR DESCRIPTION
**Pull request by theTWIXhunter**
I am ready IG

### CODE REVIEW

**Comment by theTWIXhunter** [comment]
I currently addded this in /mc/modifications/plugins but lemme know if you wantit changed to something else

**Comment by theTWIXhunter** [comment]
fixed the folder location (and the weird mm/dd/yyyy thing in the front)

**Comment by theTWIXhunter** [comment]
the Article itself is for tommorow (in the hope my brain brains a bit better then)

**Comment by theTWIXhunter** [comment]
woud I include multiverse-netherportals and/or multiverse-inventory? 
I am curently only adding mv-core and mv-portals
but a "how to link dimensons to eachother" is possible too...

**Comment by theTWIXhunter** [comment]
I think this is all I can say

**Comment by theTWIXhunter** [comment]
ready for review

**Review by iamdeka — APPROVED** [review]
(he was not ready)

**Review by iamdeka — APPROVED** [review]

**Comment by theTWIXhunter** [comment]
I still think that the second <portalname> (line: 88) shoud be changed to something like <destination> or so

**Comment by theTWIXhunter** [comment]
but Deka is "happy" so I am not gonna speak against him

**Review by Mocab — APPROVED** [review]

**Comment by Mocab** [comment]
> For future articles please fact check everything before submitting a pr

**Pull request merged**
